include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  COMMAND: rviz2
  TARGET: dev,run
  PLATFORM: amd64